/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CidadaoRouteImport } from './routes/cidadao'
import { Route as AppRouteImport } from './routes/_app'
import { Route as CidadaoIndexRouteImport } from './routes/cidadao.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as CidadaoTransparenciaRouteImport } from './routes/cidadao.transparencia'
import { Route as CidadaoPainelRouteImport } from './routes/cidadao.painel'
import { Route as CidadaoObrasRouteImport } from './routes/cidadao.obras'
import { Route as CidadaoNotificacoesRouteImport } from './routes/cidadao.notificacoes'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppObrasRouteImport } from './routes/_app.obras'
import { Route as AppMunicipiosRouteImport } from './routes/_app.municipios'
import { Route as AppMetodologiaRouteImport } from './routes/_app.metodologia'
import { Route as AppMapaRouteImport } from './routes/_app.mapa'
import { Route as AppMacaeRouteImport } from './routes/_app.macae'
import { Route as AppFornecedoresRouteImport } from './routes/_app.fornecedores'
import { Route as AppEtlRouteImport } from './routes/_app.etl'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContratosRouteImport } from './routes/_app.contratos'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppAlertasRouteImport } from './routes/_app.alertas'
import { Route as CidadaoObrasIdRouteImport } from './routes/cidadao.obras.$id'
import { Route as ApiArgusSplatRouteImport } from './routes/api.argus.$'
import { Route as AppObrasIdRouteImport } from './routes/_app.obras.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadaoRoute = CidadaoRouteImport.update({
  id: '/cidadao',
  path: '/cidadao',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadaoIndexRoute = CidadaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CidadaoRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const CidadaoTransparenciaRoute = CidadaoTransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => CidadaoRoute,
} as any)
const CidadaoPainelRoute = CidadaoPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => CidadaoRoute,
} as any)
const CidadaoObrasRoute = CidadaoObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => CidadaoRoute,
} as any)
const CidadaoNotificacoesRoute = CidadaoNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => CidadaoRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppObrasRoute = AppObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AppRoute,
} as any)
const AppMunicipiosRoute = AppMunicipiosRouteImport.update({
  id: '/municipios',
  path: '/municipios',
  getParentRoute: () => AppRoute,
} as any)
const AppMetodologiaRoute = AppMetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppMacaeRoute = AppMacaeRouteImport.update({
  id: '/macae',
  path: '/macae',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresRoute = AppFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRoute,
} as any)
const AppEtlRoute = AppEtlRouteImport.update({
  id: '/etl',
  path: '/etl',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)
const CidadaoObrasIdRoute = CidadaoObrasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CidadaoObrasRoute,
} as any)
const ApiArgusSplatRoute = ApiArgusSplatRouteImport.update({
  id: '/api/argus/$',
  path: '/api/argus/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppObrasIdRoute = AppObrasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppObrasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/cidadao': typeof CidadaoRouteWithChildren
  '/login': typeof LoginRoute
  '/alertas': typeof AppAlertasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contratos': typeof AppContratosRoute
  '/dashboard': typeof AppDashboardRoute
  '/etl': typeof AppEtlRoute
  '/fornecedores': typeof AppFornecedoresRoute
  '/macae': typeof AppMacaeRoute
  '/mapa': typeof AppMapaRoute
  '/metodologia': typeof AppMetodologiaRoute
  '/municipios': typeof AppMunicipiosRoute
  '/obras': typeof AppObrasRouteWithChildren
  '/relatorios': typeof AppRelatoriosRoute
  '/cidadao/notificacoes': typeof CidadaoNotificacoesRoute
  '/cidadao/obras': typeof CidadaoObrasRouteWithChildren
  '/cidadao/painel': typeof CidadaoPainelRoute
  '/cidadao/transparencia': typeof CidadaoTransparenciaRoute
  '/cidadao/': typeof CidadaoIndexRoute
  '/obras/$id': typeof AppObrasIdRoute
  '/api/argus/$': typeof ApiArgusSplatRoute
  '/cidadao/obras/$id': typeof CidadaoObrasIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/alertas': typeof AppAlertasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contratos': typeof AppContratosRoute
  '/dashboard': typeof AppDashboardRoute
  '/etl': typeof AppEtlRoute
  '/fornecedores': typeof AppFornecedoresRoute
  '/macae': typeof AppMacaeRoute
  '/mapa': typeof AppMapaRoute
  '/metodologia': typeof AppMetodologiaRoute
  '/municipios': typeof AppMunicipiosRoute
  '/obras': typeof AppObrasRouteWithChildren
  '/relatorios': typeof AppRelatoriosRoute
  '/cidadao/notificacoes': typeof CidadaoNotificacoesRoute
  '/cidadao/obras': typeof CidadaoObrasRouteWithChildren
  '/cidadao/painel': typeof CidadaoPainelRoute
  '/cidadao/transparencia': typeof CidadaoTransparenciaRoute
  '/': typeof AppIndexRoute
  '/cidadao': typeof CidadaoIndexRoute
  '/obras/$id': typeof AppObrasIdRoute
  '/api/argus/$': typeof ApiArgusSplatRoute
  '/cidadao/obras/$id': typeof CidadaoObrasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/cidadao': typeof CidadaoRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alertas': typeof AppAlertasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/contratos': typeof AppContratosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/etl': typeof AppEtlRoute
  '/_app/fornecedores': typeof AppFornecedoresRoute
  '/_app/macae': typeof AppMacaeRoute
  '/_app/mapa': typeof AppMapaRoute
  '/_app/metodologia': typeof AppMetodologiaRoute
  '/_app/municipios': typeof AppMunicipiosRoute
  '/_app/obras': typeof AppObrasRouteWithChildren
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/cidadao/notificacoes': typeof CidadaoNotificacoesRoute
  '/cidadao/obras': typeof CidadaoObrasRouteWithChildren
  '/cidadao/painel': typeof CidadaoPainelRoute
  '/cidadao/transparencia': typeof CidadaoTransparenciaRoute
  '/_app/': typeof AppIndexRoute
  '/cidadao/': typeof CidadaoIndexRoute
  '/_app/obras/$id': typeof AppObrasIdRoute
  '/api/argus/$': typeof ApiArgusSplatRoute
  '/cidadao/obras/$id': typeof CidadaoObrasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cidadao'
    | '/login'
    | '/alertas'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/etl'
    | '/fornecedores'
    | '/macae'
    | '/mapa'
    | '/metodologia'
    | '/municipios'
    | '/obras'
    | '/relatorios'
    | '/cidadao/notificacoes'
    | '/cidadao/obras'
    | '/cidadao/painel'
    | '/cidadao/transparencia'
    | '/cidadao/'
    | '/obras/$id'
    | '/api/argus/$'
    | '/cidadao/obras/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/alertas'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/etl'
    | '/fornecedores'
    | '/macae'
    | '/mapa'
    | '/metodologia'
    | '/municipios'
    | '/obras'
    | '/relatorios'
    | '/cidadao/notificacoes'
    | '/cidadao/obras'
    | '/cidadao/painel'
    | '/cidadao/transparencia'
    | '/'
    | '/cidadao'
    | '/obras/$id'
    | '/api/argus/$'
    | '/cidadao/obras/$id'
  id:
    | '__root__'
    | '/_app'
    | '/cidadao'
    | '/login'
    | '/_app/alertas'
    | '/_app/configuracoes'
    | '/_app/contratos'
    | '/_app/dashboard'
    | '/_app/etl'
    | '/_app/fornecedores'
    | '/_app/macae'
    | '/_app/mapa'
    | '/_app/metodologia'
    | '/_app/municipios'
    | '/_app/obras'
    | '/_app/relatorios'
    | '/cidadao/notificacoes'
    | '/cidadao/obras'
    | '/cidadao/painel'
    | '/cidadao/transparencia'
    | '/_app/'
    | '/cidadao/'
    | '/_app/obras/$id'
    | '/api/argus/$'
    | '/cidadao/obras/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CidadaoRoute: typeof CidadaoRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiArgusSplatRoute: typeof ApiArgusSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidadao': {
      id: '/cidadao'
      path: '/cidadao'
      fullPath: '/cidadao'
      preLoaderRoute: typeof CidadaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidadao/': {
      id: '/cidadao/'
      path: '/'
      fullPath: '/cidadao/'
      preLoaderRoute: typeof CidadaoIndexRouteImport
      parentRoute: typeof CidadaoRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/cidadao/transparencia': {
      id: '/cidadao/transparencia'
      path: '/transparencia'
      fullPath: '/cidadao/transparencia'
      preLoaderRoute: typeof CidadaoTransparenciaRouteImport
      parentRoute: typeof CidadaoRoute
    }
    '/cidadao/painel': {
      id: '/cidadao/painel'
      path: '/painel'
      fullPath: '/cidadao/painel'
      preLoaderRoute: typeof CidadaoPainelRouteImport
      parentRoute: typeof CidadaoRoute
    }
    '/cidadao/obras': {
      id: '/cidadao/obras'
      path: '/obras'
      fullPath: '/cidadao/obras'
      preLoaderRoute: typeof CidadaoObrasRouteImport
      parentRoute: typeof CidadaoRoute
    }
    '/cidadao/notificacoes': {
      id: '/cidadao/notificacoes'
      path: '/notificacoes'
      fullPath: '/cidadao/notificacoes'
      preLoaderRoute: typeof CidadaoNotificacoesRouteImport
      parentRoute: typeof CidadaoRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/obras': {
      id: '/_app/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof AppObrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/municipios': {
      id: '/_app/municipios'
      path: '/municipios'
      fullPath: '/municipios'
      preLoaderRoute: typeof AppMunicipiosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metodologia': {
      id: '/_app/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof AppMetodologiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mapa': {
      id: '/_app/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/macae': {
      id: '/_app/macae'
      path: '/macae'
      fullPath: '/macae'
      preLoaderRoute: typeof AppMacaeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fornecedores': {
      id: '/_app/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/etl': {
      id: '/_app/etl'
      path: '/etl'
      fullPath: '/etl'
      preLoaderRoute: typeof AppEtlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos': {
      id: '/_app/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alertas': {
      id: '/_app/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/cidadao/obras/$id': {
      id: '/cidadao/obras/$id'
      path: '/$id'
      fullPath: '/cidadao/obras/$id'
      preLoaderRoute: typeof CidadaoObrasIdRouteImport
      parentRoute: typeof CidadaoObrasRoute
    }
    '/api/argus/$': {
      id: '/api/argus/$'
      path: '/api/argus/$'
      fullPath: '/api/argus/$'
      preLoaderRoute: typeof ApiArgusSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/obras/$id': {
      id: '/_app/obras/$id'
      path: '/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof AppObrasIdRouteImport
      parentRoute: typeof AppObrasRoute
    }
  }
}

interface AppObrasRouteChildren {
  AppObrasIdRoute: typeof AppObrasIdRoute
}

const AppObrasRouteChildren: AppObrasRouteChildren = {
  AppObrasIdRoute: AppObrasIdRoute,
}

const AppObrasRouteWithChildren = AppObrasRoute._addFileChildren(
  AppObrasRouteChildren,
)

interface AppRouteChildren {
  AppAlertasRoute: typeof AppAlertasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContratosRoute: typeof AppContratosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEtlRoute: typeof AppEtlRoute
  AppFornecedoresRoute: typeof AppFornecedoresRoute
  AppMacaeRoute: typeof AppMacaeRoute
  AppMapaRoute: typeof AppMapaRoute
  AppMetodologiaRoute: typeof AppMetodologiaRoute
  AppMunicipiosRoute: typeof AppMunicipiosRoute
  AppObrasRoute: typeof AppObrasRouteWithChildren
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertasRoute: AppAlertasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContratosRoute: AppContratosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEtlRoute: AppEtlRoute,
  AppFornecedoresRoute: AppFornecedoresRoute,
  AppMacaeRoute: AppMacaeRoute,
  AppMapaRoute: AppMapaRoute,
  AppMetodologiaRoute: AppMetodologiaRoute,
  AppMunicipiosRoute: AppMunicipiosRoute,
  AppObrasRoute: AppObrasRouteWithChildren,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CidadaoObrasRouteChildren {
  CidadaoObrasIdRoute: typeof CidadaoObrasIdRoute
}

const CidadaoObrasRouteChildren: CidadaoObrasRouteChildren = {
  CidadaoObrasIdRoute: CidadaoObrasIdRoute,
}

const CidadaoObrasRouteWithChildren = CidadaoObrasRoute._addFileChildren(
  CidadaoObrasRouteChildren,
)

interface CidadaoRouteChildren {
  CidadaoNotificacoesRoute: typeof CidadaoNotificacoesRoute
  CidadaoObrasRoute: typeof CidadaoObrasRouteWithChildren
  CidadaoPainelRoute: typeof CidadaoPainelRoute
  CidadaoTransparenciaRoute: typeof CidadaoTransparenciaRoute
  CidadaoIndexRoute: typeof CidadaoIndexRoute
}

const CidadaoRouteChildren: CidadaoRouteChildren = {
  CidadaoNotificacoesRoute: CidadaoNotificacoesRoute,
  CidadaoObrasRoute: CidadaoObrasRouteWithChildren,
  CidadaoPainelRoute: CidadaoPainelRoute,
  CidadaoTransparenciaRoute: CidadaoTransparenciaRoute,
  CidadaoIndexRoute: CidadaoIndexRoute,
}

const CidadaoRouteWithChildren =
  CidadaoRoute._addFileChildren(CidadaoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CidadaoRoute: CidadaoRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiArgusSplatRoute: ApiArgusSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
